#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Conduit.API/ && \
    dotnet build src/Conduit.API/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Conduit.API/Conduit.API.csproj --launch-profile web"
