/*
 * Conduit API
 *
 * Conduit API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using App.Content.Domain.Contracts.Operations.Queries.GetTags;
using App.Core.PipelineBehaviors.OperationResponse;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Conduit.API.Attributes;
using Conduit.API.Models;
using MediatR;

namespace Conduit.API.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : OperationResponseController
    {
        public DefaultApiController(IMediator mediator) : base(mediator)
        {
        }

        /// <summary>
        /// Get tags
        /// </summary>
        /// <remarks>Get tags. Auth not required</remarks>
        /// <response code="200">OK</response>
        /// <response code="422">Unexpected error</response>
        [HttpGet]
        [AllowAnonymous]
        [Route("/api/tags")]
        [ValidateModelState]
        [SwaggerOperation("TagsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(TagsResponse), description: "OK")]
        [SwaggerResponse(statusCode: 422, type: typeof(GenericErrorModel), description: "Unexpected error")]
        public virtual async Task<IActionResult> TagsGet()
        {
            var getTagsQueryResult = await Mediator.Send(new GetTagsQuery());

            if ( getTagsQueryResult.Result != OperationResult.Success )
                return UnsuccessfulResponseResult(getTagsQueryResult);

            return Ok(new TagsResponse
            {
                Tags = getTagsQueryResult.Response.Tags.ToList()
            });
        }
    }
}
