name: batect lint:dotnet:format
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v4.2.3
        with:
          path: .batect/caches
          key: batect-${{ hashFiles('batect') }}

      - name: batect lint:dotnet:format
        run: ./batect lint:dotnet:format
